### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gguogguo** [roydejong/chromium-unity-server#4]
Hello!

Although you said It's under construction, I found this code is wonderful start point for in-game browser for Unity!

I was wondering what the intended license for this project is. 
Could you specify what license is you intended?

Sincerly yours
Park.

**Comment by roydejong** [comment]
Thanks - you can consider this project MIT licensed. I'll add a license file now.

**Comment by gguogguo** [comment]
Thank you!!!!
