### ISSUE TITLE
Why Chromium doesn't support Android?

### ISSUE THREAD

**Issue by kris-w-dev** [roydejong/chromium-unity-server#8]
I hope my website can run on VR devices. This website needs to use VideoEncoder, but webview and gecko do not support VideoEncoder, So I want to know why Chromium doesn't support Android?

**Comment by roydejong** [comment]
I think you may have opened this issue in the wrong project?

This project embeds Chromium into a process for use with games built on the Unity engine. 

Chromium / Chrome does support Android.
